import Navbar from '@/components/layout/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Custos Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <link rel='shortcut icon' href='/favicon/favicon.ico' />
      <body className={inter.className}>{children}
        <Navbar />
      </body>
    </html>
  )
}